#php code that is executed when repeated survey procedure (e.g. Experience Sampling Method) is started the first time:
#it will initialize a semi-random sampling procedure, where participants are invited to the survey at random timeslots, 
#but only between 10am and 10pm,
#and with a minimal interval of 1 hour between invitations.

#this specific code is optimized for SoSciSurvey, but can be adapted to other survey tools as well.


$id = value('I124_01'); //get pseundonmyized id
$data = dbLoad($id); //load/request data with ID from additional database (here additional databse of survey tool SoSciSurvey: dbLoad is a SoSciSurvey specific function)

$elements = count($data); //count number of elements with ID in additional database, to later check whether it is the first survey of repeated, longitudinal questionaires

put('S301_01', $elements); //additionally put number of elements with ID in conventional survey tool variable S301_01, for additional reliability check or other purposes

$time = time(); //get current time


$date24 = convertDateTime($time,null,"H:i:s");  //convert current time to 24h format





//calculate time difference to 10am next day


$minuten = substr($date24,3,2);

$till_full_hour = 60-$minuten;

$hour = substr($date24,0,2);
$till_10_am = 33.00 - $hour;

$d = (($till_10_am*3600) + ($till_full_hour*60));   //time difference to 10am next day in seconds, will later in code be added to every time generated by the code, 
                                                    //so that the time is always between 10am and 10pm


         


if ($elements == 1) {  //check whether it is the first survey of repeated, longitudinal questionaires. 
                      //Only then the code is executed and initalizes the semi-random sampling procedure for however many days the survey is repeated,
                      //e.g. 6 prompts per day for 14 days in a row


//Ticker-Variable

//$number = 0;

//dbSet("Ticker_" . value('I124_01') . "_NR" . $number, $number);   //save ticker variable in additional database (dbSet here SoSciSurvey specific function), 
                                                                    //so code is not executed in subsequent surveys



$invite = array();

function generateTime() {

//first random time
$t1 = random(0,43200);
$invite[] = $t1;


//new random times are forbidden to be in this timespace
$reservedmax = $t1 + 3600;
$reservedmin = $t1 - 3600;


//generate new random time
$t2 = random(0,43200);


//if in forbidden timespace, generate new random time till constraints
//are fullfilled

while ($t2 < $reservedmax && $t2 > $reservedmin) {

$t2 = random(0,43200);

}

$invite[] = $t2;

$reservedmax2 = $t2 + 3600;
$reservedmin2 = $t2 - 3600;




$t3 = random(0,43200);

while (($t3 < $reservedmax && $t3 > $reservedmin) OR 
($t3 < $reservedmax2 && $t3 > $reservedmin2)) {

$t3 = random(0,43200);

}

$invite[] = $t3;

$reservedmax3 = $t3 + 3600;
$reservedmin3 = $t3 - 3600;





$t4 = random(0,43200);

while (($t4 < $reservedmax && $t4 > $reservedmin) OR ($t4 < $reservedmax2 && $t4 > $reservedmin2) OR ($t4 < $reservedmax3 && $t4 > $reservedmin3)) {

$t4 = random(0,43200);

}

$invite[] = $t4;

$reservedmax4 = $t4 + 3600;
$reservedmin4 = $t4 - 3600;





$t5 = random(0,43200);

while (($t5 < $reservedmax && $t5 > $reservedmin) OR ($t5 < $reservedmax2 && $t5 > $reservedmin2) OR ($t5 < $reservedmax3 && $t5 > $reservedmin3) 
OR ($t5 < $reservedmax4 && $t5 > $reservedmin4)) {

$t5 = random(0,43200);

}

$invite[] = $t5;

$reservedmax5 = $t5 + 3600;
$reservedmin5 = $t5 - 3600;





$t6 = random(0,43200);

while (($t6 < $reservedmax && $t6 > $reservedmin) OR ($t6 < $reservedmax2 && $t6 > $reservedmin2) OR ($t6 < $reservedmax3 && $t6 > $reservedmin3) 
OR ($t6 < $reservedmax4 && $t6 > $reservedmin4) OR ($t6 < $reservedmax5 && $t6 > $reservedmin5)) {

$t6 = random(0,43200);

}

$invite[] = $t6;
$invite2 = $invite;
//$reservedmax6 = $t6 + 3600;
//$reservedmin6 = $t6 - 3600;


/*
//additional check for errors, not needed
foreach($invite as $inv) {

	foreach($invite2 as $inv2) {
    
    if ($inv == $inv2) {
    
    	continue;
        
        }
    

 $dist = $inv - $inv2;
 $dist = abs($d);
 //print($d);
 if ($dist < 1801) {
 //print("Fehler");
 return generateTime();
 }

 }
 }
//error check over
*/



asort($invite); //sort array in ascending order
//print_r($invite);
return $invite;
}


$invitee = generateTime();




//initialize generated times for day 1 of longitundinal survey (in this code, this will be the next day after the first survey is filled out)

$tag1 = array();

foreach($invitee as $inv) {
$inv = $inv + $d;   //add time difference to 10am next day to every time generated by the code, so that the time is always between 10am and 10pm

$tag1[] = $inv;

}

//Array settings for SoSciSurvey specific function mailSchedule, specifiying that link to survey is only valid for 30 minutes

 
$settings = array("expire" => 1800);




//now the mails or SMS are scheduled for the next day, and will automatically be sent out at the specified times
//survey pompt times are saved as survey variables, for reliability checks or other purposes, e.g. analysis
//'yourmailhere@mail.com' specifies from which mail the invitations will be sent

//Invitations day 1
//Einladungen Tag 1

mailSchedule($id, 3, $tag1[0], ['expire' => $tag1[0] + 3600, 'to.email' => 'yourmailhere@mail.com']); 
put('S401_01', $tag1[0]);

mailSchedule($id, 4, $tag1[1], ['expire' => $tag1[1] + 3600, 'to.email' => 'yourmailhere@mail.com']);
put('S401_02', $tag1[1]);

mailSchedule($id, 5, $tag1[2], ['expire' => $tag1[2] + 3600, 'to.email' => 'yourmailhere@mail.com']);
put('S401_03', $tag1[2]);

mailSchedule($id, 6, $tag1[3], ['expire' => $tag1[3] + 3600, 'to.email' => 'yourmailhere@mail.com']);
put('S401_04', $tag1[3]);

mailSchedule($id, 7, $tag1[4], ['expire' => $tag1[4] + 3600, 'to.email' => 'yourmailhere@mail.com']);
put('S401_05', $tag1[4]);

mailSchedule($id, 8, $tag1[5], ['expire' => $tag1[5] + 3600, 'to.email' => 'yourmailhere@mail.com']);
put('S401_06', $tag1[5]);




//Einladungen Tag 2

$invite2 = generateTime();

$tag2 = array();

foreach($invite2 as $inv2) {
$inv2 = $inv2+$d + 86400; //+86400 is one day in seconds, so that the invitations are sent out on the second day of the study
 
$tag2[] = $inv2;

 

    
}


mailSchedule($id, 10, $tag2[0], ['expire' => $tag2[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_07', $tag2[0]);

mailSchedule($id, 11, $tag2[1], ['expire' => $tag2[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_08', $tag2[1]);

mailSchedule($id, 12, $tag2[2], ['expire' => $tag2[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_09', $tag2[2]);

mailSchedule($id, 13, $tag2[3], ['expire' => $tag2[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_10', $tag2[3]);

mailSchedule($id, 14, $tag2[4], ['expire' => $tag2[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_11', $tag2[4]);

mailSchedule($id, 15, $tag2[5], ['expire' => $tag2[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_12', $tag2[5]);



//repeat procedure for all subsequent days you want to send out invitations






//Einladungen Tag 3

$invite3 = generateTime();

$tag3 = array();

foreach($invite3 as $inv3) {
$inv3 = $inv3 +$d + 86400 + 86400;
 
$tag3[] = $inv3;

    
}


mailSchedule($id, 20, $tag3[0], ['expire' => $tag3[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_13', $tag3[0]);

mailSchedule($id, 21, $tag3[1], ['expire' => $tag3[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_14', $tag3[1]);

mailSchedule($id, 22, $tag3[2], ['expire' => $tag3[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_15', $tag3[2]);

mailSchedule($id, 23, $tag3[3], ['expire' => $tag3[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_16', $tag3[3]);

mailSchedule($id, 24, $tag3[4], ['expire' => $tag3[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_17', $tag3[4]);

mailSchedule($id, 25, $tag3[5], ['expire' => $tag3[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_18', $tag3[5]);





//Einladungen Tag 4

$invite4 = generateTime();

$tag4 = array();

foreach($invite4 as $inv4) {
$inv4 = $inv4+$d + 86400 + 86400 + 86400;
 
$tag4[] = $inv4;

 

    
}


mailSchedule($id, 26, $tag4[0], ['expire' => $tag4[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_19', $tag4[0]);

mailSchedule($id, 27, $tag4[1], ['expire' => $tag4[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_20', $tag4[1]);

mailSchedule($id, 28, $tag4[2], ['expire' => $tag4[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_21', $tag4[2]);

mailSchedule($id, 29, $tag4[3], ['expire' => $tag4[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_22', $tag4[3]);

mailSchedule($id, 30, $tag4[4], ['expire' => $tag4[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_23', $tag4[4]);

mailSchedule($id, 31, $tag4[5], ['expire' => $tag4[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_24', $tag4[5]);





//Einladungen Tag 5

$invite5 = generateTime();

$tag5 = array();

foreach($invite5 as $inv5) {
$inv5 = $inv5 +$d + 86400 + 86400 + 86400 + 86400;
 
$tag5[] = $inv5;

 

    
}


mailSchedule($id, 32, $tag5[0], ['expire' => $tag5[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_25', $tag5[0]);

mailSchedule($id, 33, $tag5[1], ['expire' => $tag5[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_26', $tag5[1]);

mailSchedule($id, 34, $tag5[2], ['expire' => $tag5[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_27', $tag5[2]);

mailSchedule($id, 35, $tag5[3], ['expire' => $tag5[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_28', $tag5[3]);

mailSchedule($id, 36, $tag5[4], ['expire' => $tag5[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_29', $tag5[4]);

mailSchedule($id, 37, $tag5[5], ['expire' => $tag5[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_30', $tag5[5]);




//Einladungen Tag 6

$invite6 = generateTime();

$tag6 = array();

foreach($invite6 as $inv6) {
$inv6 = $inv6 +$d + 86400 + 86400 + 86400 + 86400 + 86400;
 
$tag6[] = $inv6;

 

    
}


mailSchedule($id, 38, $tag6[0], ['expire' => $tag6[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_31', $tag6[0]);

mailSchedule($id, 39, $tag6[1], ['expire' => $tag6[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_32', $tag6[1]);

mailSchedule($id, 40, $tag6[2], ['expire' => $tag6[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_33', $tag6[2]);

mailSchedule($id, 41, $tag6[3], ['expire' => $tag6[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_34', $tag6[3]);

mailSchedule($id, 42, $tag6[4], ['expire' => $tag6[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_35', $tag6[4]);

mailSchedule($id, 43, $tag6[5], ['expire' => $tag6[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_36', $tag6[5]);




//Einladungen Tag 7

$invite7 = generateTime();

$tag7 = array();

foreach($invite7 as $inv7) {
$inv7 = $inv7 +$d + 86400 + 86400 + 86400 + 86400 + 86400 + 86400;
 
$tag7[] = $inv7;

 

    
}


mailSchedule($id, 44, $tag7[0], ['expire' => $tag7[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_37', $tag7[0]);

mailSchedule($id, 45, $tag7[1], ['expire' => $tag7[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_38', $tag7[1]);

mailSchedule($id, 46, $tag7[2], ['expire' => $tag7[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_39', $tag7[2]);

mailSchedule($id, 47, $tag7[3], ['expire' => $tag7[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_40', $tag7[3]);

mailSchedule($id, 48, $tag7[4], ['expire' => $tag7[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_41', $tag7[4]);

mailSchedule($id, 49, $tag7[5], ['expire' => $tag7[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_42', $tag7[5]);




//Einladungen Tag 8

$invite8 = generateTime();

$tag8 = array();

foreach($invite8 as $inv8) {
$inv8 = $inv8 +$d + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400;
 
$tag8[] = $inv8;

 

    
}


mailSchedule($id, 50, $tag8[0], ['expire' => $tag8[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_43', $tag8[0]);

mailSchedule($id, 51, $tag8[1], ['expire' => $tag8[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_44', $tag8[1]);

mailSchedule($id, 52, $tag8[2], ['expire' => $tag8[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_45', $tag8[2]);

mailSchedule($id, 53, $tag8[3], ['expire' => $tag8[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_46', $tag8[3]);

mailSchedule($id, 54, $tag8[4], ['expire' => $tag8[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_47', $tag8[4]);

mailSchedule($id, 55, $tag8[5], ['expire' => $tag8[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_48', $tag8[5]);




//Einladungen Tag 9

$invite9 = generateTime();

$tag9 = array();

foreach($invite9 as $inv9) {
$inv9 = $inv9 +$d + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400;
 
$tag9[] = $inv9;

 

    
}


mailSchedule($id, 56, $tag9[0], ['expire' => $tag9[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_49', $tag9[0]);

mailSchedule($id, 57, $tag9[1], ['expire' => $tag9[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_50', $tag9[1]);

mailSchedule($id, 58, $tag9[2], ['expire' => $tag9[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_51', $tag9[2]);

mailSchedule($id, 59, $tag9[3], ['expire' => $tag9[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_52', $tag9[3]);

mailSchedule($id, 60, $tag9[4], ['expire' => $tag9[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_53', $tag9[4]);

mailSchedule($id, 61, $tag9[5], ['expire' => $tag9[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_54', $tag9[5]);



//Einladungen Tag 10

$invite10 = generateTime();

$tag10 = array();

foreach($invite10 as $inv10) {
$inv10 = $inv10 +$d + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 +86400 + 86400 + 86400;
 
$tag10[] = $inv10;

 

    
}


mailSchedule($id, 62, $tag10[0], ['expire' => $tag10[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_55', $tag10[0]);

mailSchedule($id, 63, $tag10[1], ['expire' => $tag10[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_56', $tag10[1]);

mailSchedule($id, 64, $tag10[2], ['expire' => $tag10[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_57', $tag10[2]);

mailSchedule($id, 65, $tag10[3], ['expire' => $tag10[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_58', $tag10[3]);

mailSchedule($id, 66, $tag10[4], ['expire' => $tag10[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_59', $tag10[4]);

mailSchedule($id, 67, $tag10[5], ['expire' => $tag10[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_60', $tag10[5]);





//Einladungen Tag 11

$invite11 = generateTime();

$tag11 = array();

foreach($invite11 as $inv11) {
$inv11 = $inv11 +$d + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400;
 
$tag11[] = $inv11;

    
}


mailSchedule($id, 68, $tag11[0], ['expire' => $tag11[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_61', $tag11[0]);

mailSchedule($id, 69, $tag11[1], ['expire' => $tag11[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_62', $tag11[1]);

mailSchedule($id, 70, $tag11[2], ['expire' => $tag11[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_63', $tag11[2]);

mailSchedule($id, 71, $tag11[3], ['expire' => $tag11[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_64', $tag11[3]);

mailSchedule($id, 72, $tag11[4], ['expire' => $tag11[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_65', $tag11[4]);

mailSchedule($id, 73, $tag11[5], ['expire' => $tag11[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_66', $tag11[5]);




//Einladungen Tag 12

$invite12 = generateTime();

$tag12 = array();

foreach($invite12 as $inv12) {
$inv12 = $inv12 +$d + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400;
 
$tag12[] = $inv12;
  
}


mailSchedule($id, 74, $tag12[0], ['expire' => $tag12[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_67', $tag12[0]);

mailSchedule($id, 75, $tag12[1], ['expire' => $tag12[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_68', $tag12[1]);

mailSchedule($id, 76, $tag12[2], ['expire' => $tag12[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_69', $tag12[2]);

mailSchedule($id, 77, $tag12[3], ['expire' => $tag12[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_70', $tag12[3]);

mailSchedule($id, 78, $tag12[4], ['expire' => $tag12[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_71', $tag12[4]);

mailSchedule($id, 79, $tag12[5], ['expire' => $tag12[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_72', $tag12[5]);





//Einladungen Tag 13

$invite13 = generateTime();

$tag13 = array();

foreach($invite13 as $inv13) {
$inv13 = $inv13 +$d + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400;
 
$tag13[] = $inv13;

 

    
}


mailSchedule($id, 80, $tag13[0], ['expire' => $tag13[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_73', $tag13[0]);

mailSchedule($id, 81, $tag13[1], ['expire' => $tag13[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_74', $tag13[1]);

mailSchedule($id, 82, $tag13[2], ['expire' => $tag13[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_75', $tag13[2]);

mailSchedule($id, 83, $tag13[3], ['expire' => $tag13[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_76', $tag13[3]);

mailSchedule($id, 84, $tag13[4], ['expire' => $tag13[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_77', $tag13[4]);

mailSchedule($id, 85, $tag13[5], ['expire' => $tag13[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_78', $tag13[5]);






//Einladungen Tag 14

$invite14 = generateTime();

$tag14 = array();

foreach($invite14 as $inv14) {
$inv14 = $inv14 +$d + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400 + 86400;
 
$tag14[] = $inv14;

 

    
}


mailSchedule($id, 86, $tag14[0], ['expire' => $tag14[0] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_79', $tag14[0]);

mailSchedule($id, 87, $tag14[1], ['expire' => $tag14[1] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_80', $tag14[1]);

mailSchedule($id, 88, $tag14[2], ['expire' => $tag14[2] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_81', $tag14[2]);

mailSchedule($id, 89, $tag14[3], ['expire' => $tag14[3] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_82', $tag14[3]);

mailSchedule($id, 90, $tag14[4], ['expire' => $tag14[4] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_83', $tag14[4]);

mailSchedule($id, 91, $tag14[5], ['expire' => $tag14[5] + 3600, 'to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_84', $tag14[5]);



$exitzeit = $tag14[5] + 3600;

//Exit Survey
mailSchedule($id, 19, $exitzeit, ['to.email' => 'musikstreamingstudie@uni-mainz.de']);
put('S401_85', $exitzeit);

};